/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qin_ndk_ndk_NdkTools */

#ifndef _Included_com_qin_ndk_ndk_NdkTools
#define _Included_com_qin_ndk_ndk_NdkTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qin_ndk_ndk_NdkTools
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qin_ndk_ndk_NdkTools_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
